Debian/Ubuntu: if software installation fails, update package indices and retry

diff --git a/fahinstall b/fahinstall
--- a/fahinstall
+++ b/fahinstall
@@ -166,7 +166,14 @@ TARGET=$(eval echo ~$SUDO_USER/fah)
 
 #install software
 echo ==== Installing required software, this may take a few minutes ...
-which apt-get > /dev/null 2>&1 && apt-get install -qq openssh-server screen samba mcelog pastebinit build-essential
+if which apt-get > /dev/null 2>&1 ; then
+	PACKAGES_DEBIAN="openssh-server screen samba mcelog pastebinit build-essential"
+	if ! apt-get install -qq $PACKAGES_DEBIAN ; then
+		# If installation fails -- update package indices and retry
+		apt-get update -qq
+		apt-get install -qq $PACKAGES_DEBIAN
+	fi
+fi
 which yum > /dev/null 2>&1 && yum -y -q install tar bzip2 screen samba mcelog gcc make
 
 echo ==== Applying OS tweaks ...
